name: Package with Maven, Build Docker Image, and push to DockerHub

on:
  push:
    branches:
      - master
  release:
    types: [created]

jobs:
  build-java-package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Build app with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: Archive build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: app-artifact
          path: target/*.jar
          
  build-push-docker:
    needs: build-java-package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: app-artifact
          path: target/
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kiii-bookstore:latest
